using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace SalesforceAPI.Dtos
{
    public class PractitionerLicenseCertificationDto
    {
        public string? Credentialing_Profile_Id__c { get; set; }
        public string? RecordTypeId { get; set; }
        public LicenseCertificationTypeCEnum? LicenseCertification_Type__c { get; set; }
        public LicenseTypesLARACEnum? License_Types_LARA__c { get; set; }
        public string? Other_License_Type__c { get; set; }
        public BoardCertificationsCEnum? Board_Certifications__c { get; set; }
        public string? Other_Board_Certification__c { get; set; }
        public NursingCertificationsCEnum? Nursing_Certifications__c { get; set; }
        public DateTime Expiration_Date__c { get; set; }
        public bool File_Uploaded__c { get; set; }
        public LicenseCertificationStatusCEnum? LicenseCertification_Status__c { get; set; }

        public enum LicenseCertificationTypeCEnum
        {
            [EnumMember(Value = "License")]
            LicenseEnum = 0,
            [EnumMember(Value = "Certification")]
            CertificationEnum = 1,
            [EnumMember(Value = "Nursing Certification")]
            NursingCertificationEnum = 2
        }
        public enum LicenseTypesLARACEnum
        {
            [EnumMember(Value = "Acupuncture")]
            AcupunctureEnum = 0,
            [EnumMember(Value = "Audiology")]
            AudiologyEnum = 1,
            [EnumMember(Value = "Addiction Medicine")]
            AddictionMedicineEnum = 2,
            [EnumMember(Value = "Behavior Analysts")]
            BehaviorAnalystsEnum = 3,
            [EnumMember(Value = "Counseling")]
            CounselingEnum = 4,
            [EnumMember(Value = "Genetic Counseling")]
            GeneticCounselingEnum = 5,
            [EnumMember(Value = "Marriage and Family Therapy")]
            MarriageAndFamilyTherapyEnum = 6,
            [EnumMember(Value = "Massage Therapy")]
            MassageTherapyEnum = 7,
            [EnumMember(Value = "Medicine")]
            MedicineEnum = 8,
            [EnumMember(Value = "Nursing")]
            NursingEnum = 9,
            [EnumMember(Value = "Nursing Home Administrator")]
            NursingHomeAdministratorEnum = 10,
            [EnumMember(Value = "Occupational Therapy")]
            OccupationalTherapyEnum = 11,
            [EnumMember(Value = "Osteopathic Medicine & Surgery")]
            OsteopathicMedicineSurgeryEnum = 12,
            [EnumMember(Value = "Pharmacy")]
            PharmacyEnum = 13,
            [EnumMember(Value = "Physical Therapy")]
            PhysicalTherapyEnum = 14,
            [EnumMember(Value = "Physician Assistant (PA)")]
            PhysicianAssistantPAEnum = 15,
            [EnumMember(Value = "Psychology")]
            PsychologyEnum = 16,
            [EnumMember(Value = "Respiratory Care")]
            RespiratoryCareEnum = 17,
            [EnumMember(Value = "Social Worker")]
            SocialWorkerEnum = 18,
            [EnumMember(Value = "Speech-Language Pathology")]
            SpeechLanguagePathologyEnum = 19,
            [EnumMember(Value = "Nurse Practitioner (NP)")]
            NursePractitionerNPEnum = 20,
            [EnumMember(Value = "Other")]
            OtherEnum = 21,
            [EnumMember(Value = "Psychiatry")]
            PsychiatryEnum = 22
        }

        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BoardCertificationsCEnum
        {
            [EnumMember(Value = "MCBAP - MI Certification Board for Addiction Professionals")]
            MCBAPMICertificationBoardForAddictionProfessionalsEnum = 0,
            [EnumMember(Value = "AMA - American Medical Association")]
            AMAAmericanMedicalAssociationEnum = 1,
            [EnumMember(Value = "ABPM - American Board of Preventative Medicine")]
            ABPMAmericanBoardOfPreventativeMedicineEnum = 2,
            [EnumMember(Value = "BACB - Behavior Analyst Certification Board")]
            BACBBehaviorAnalystCertificationBoardEnum = 3,
            [EnumMember(Value = "ABPN - American Board of Psychiatry and Neurology")]
            ABPNAmericanBoardOfPsychiatryAndNeurologyEnum = 4,
            [EnumMember(Value = "ABFM - American Board of Family Medicine")]
            ABFMAmericanBoardOfFamilyMedicineEnum = 5,
            [EnumMember(Value = "ABIM - American Board of Internal Medicine")]
            ABIMAmericanBoardOfInternalMedicineEnum = 6,
            [EnumMember(Value = "ABNS - American Board of Neurological Surgery")]
            ABNSAmericanBoardOfNeurologicalSurgeryEnum = 7,
            [EnumMember(Value = "ABEM - American Board of Emergency Medicine")]
            ABEMAmericanBoardOfEmergencyMedicineEnum = 8,
            [EnumMember(Value = "NBCOT - National Board for Certification in Occupational Therapy")]
            NBCOTNationalBoardForCertificationInOccupationalTherapyEnum = 9,
            [EnumMember(Value = "AOA - American Osteopathic Association Board Certification")]
            AOAAmericanOsteopathicAssociationBoardCertificationEnum = 10,
            [EnumMember(Value = "BPS - Board of Pharmacy Specialties")]
            BPSBoardOfPharmacySpecialtiesEnum = 11,
            [EnumMember(Value = "APTA MI - American Physical Therapy Association (MI)")]
            APTAMIAmericanPhysicalTherapyAssociationMIEnum = 12,
            [EnumMember(Value = "NCCPA - National Commission for Certifying Physician Assistants")]
            NCCPANationalCommissionForCertifyingPhysicianAssistantsEnum = 13,
            [EnumMember(Value = "ABPP - American Board of Professional Psychology")]
            ABPPAmericanBoardOfProfessionalPsychologyEnum = 14,
            [EnumMember(Value = "NBRC - National Board for Respiratory Care")]
            NBRCNationalBoardForRespiratoryCareEnum = 15,
            [EnumMember(Value = "BCD - Board Certified Diplomate in Clinical Social Work")]
            BCDBoardCertifiedDiplomateInClinicalSocialWorkEnum = 16,
            [EnumMember(Value = "ANCDS - Academy of Neurologic Communication Disorders and Sciences")]
            ANCDSAcademyOfNeurologicCommunicationDisordersAndSciencesEnum = 17,
            [EnumMember(Value = "AANPCB - American Academy of Nurse Practitioners Certification Board")]
            AANPCBAmericanAcademyOfNursePractitionersCertificationBoardEnum = 18,
            [EnumMember(Value = "Other")]
            OtherEnum = 19
        }

        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum NursingCertificationsCEnum
        {
            [EnumMember(Value = "Adult-Gerontology Primary Care Nurse Practitioner")]
            AdultGerontologyPrimaryCareNursePractitionerEnum = 0,
            [EnumMember(Value = "Advanced HIV/AIDS Certified Registered Nurse")]
            AdvancedHIVAIDSCertifiedRegisteredNurseEnum = 1,
            [EnumMember(Value = "Clinical Nurse Specialist; Wellness through Acute Care (Adult-Gerontology)")]
            ClinicalNurseSpecialistWellnessThroughAcuteCareAdultGerontologyEnum = 2,
            [EnumMember(Value = "Clinical Nurse Specialist; Wellness through Acute Care (Neonatal)")]
            ClinicalNurseSpecialistWellnessThroughAcuteCareNeonatalEnum = 3,
            [EnumMember(Value = "Clinical Nurse Specialist, Wellness through Acute Care (Pediatric)")]
            ClinicalNurseSpecialistWellnessThroughAcuteCarePediatricEnum = 4,
            [EnumMember(Value = "Advanced Certified Hospice and Palliative Nurse")]
            AdvancedCertifiedHospiceAndPalliativeNurseEnum = 5,
            [EnumMember(Value = "Acute Care Nurse Practitioner")]
            AcuteCareNursePractitionerEnum = 6,
            [EnumMember(Value = "Acute Care Nurse Practitioner (Adult-Gerontology)")]
            AcuteCareNursePractitionerAdultGerontologyEnum = 7,
            [EnumMember(Value = "Adult Health Clinical Nurse Specialist")]
            AdultHealthClinicalNurseSpecialistEnum = 8,
            [EnumMember(Value = "HIV/AIDS Certified Registered Nurse")]
            HIVAIDSCertifiedRegisteredNurseEnum = 9,
            [EnumMember(Value = "Advanced Diabetes Management (specialty certification, retired exam)")]
            AdvancedDiabetesManagementSpecialtyCertificationRetiredExamEnum = 10,
            [EnumMember(Value = "Advanced Diabetes Management")]
            AdvancedDiabetesManagementEnum = 11,
            [EnumMember(Value = "Certified Asthma Educator")]
            CertifiedAsthmaEducatorEnum = 12,
            [EnumMember(Value = "Advanced Forensic Nursing")]
            AdvancedForensicNursingEnum = 13,
            [EnumMember(Value = "Adult-Gerontology Acute Care Nurse Practitioner")]
            AdultGerontologyAcuteCareNursePractitionerEnum = 14,
            [EnumMember(Value = "Adult-Gerontology Clinical Nurse Specialist")]
            AdultGerontologyClinicalNurseSpecialistEnum = 15,
            [EnumMember(Value = "Genetics Nursing, Advanced")]
            GeneticsNursingAdvancedEnum = 16,
            [EnumMember(Value = "Advanced Holistic Nurse, Board Certified")]
            AdvancedHolisticNurseBoardCertifiedEnum = 17,
            [EnumMember(Value = "Adult Nurse Practitioner")]
            AdultNursePractitionerEnum = 18,
            [EnumMember(Value = "Acute Care Nurse Practitioner (Adult)")]
            AcuteCareNursePractitionerAdultEnum = 19,
            [EnumMember(Value = "Advanced Oncology Certified Nurse")]
            AdvancedOncologyCertifiedNurseEnum = 20,
            [EnumMember(Value = "Advanced Oncology Certified Nurse Practitioner")]
            AdvancedOncologyCertifiedNursePractitionerEnum = 21,
            [EnumMember(Value = "Advanced Oncology Certified Clinical Nurse Specialist")]
            AdvancedOncologyCertifiedClinicalNurseSpecialistEnum = 22,
            [EnumMember(Value = "Advanced Practice Holistic Nurse")]
            AdvancedPracticeHolisticNurseEnum = 23,
            [EnumMember(Value = "Board Certified-Advanced Diabetes Management")]
            BoardCertifiedAdvancedDiabetesManagementEnum = 24,
            [EnumMember(Value = "Blood & Marrow Transplant Certified Nurse")]
            BloodMarrowTransplantCertifiedNurseEnum = 25,
            [EnumMember(Value = "Electronic Fetal Monitoring")]
            ElectronicFetalMonitoringEnum = 26,
            [EnumMember(Value = "Neonatal Pediatric Transport")]
            NeonatalPediatricTransportEnum = 27,
            [EnumMember(Value = "Certified Aesthetic Nurse Specialist")]
            CertifiedAestheticNurseSpecialistEnum = 28,
            [EnumMember(Value = "Certified Ambulatory Perianesthesia Nurse")]
            CertifiedAmbulatoryPerianesthesiaNurseEnum = 29,
            [EnumMember(Value = "Certified Addictions Registered Nurse")]
            CertifiedAddictionsRegisteredNurseEnum = 30,
            [EnumMember(Value = "Certified Addictions Registered Nurse - Advanced Practice")]
            CertifiedAddictionsRegisteredNurseAdvancedPracticeEnum = 31,
            [EnumMember(Value = "Certified Breast Feeding Counselor")]
            CertifiedBreastFeedingCounselorEnum = 32,
            [EnumMember(Value = "Certified Breast Care Nurse")]
            CertifiedBreastCareNurseEnum = 33,
            [EnumMember(Value = "Correctional Behavioral Health Certification")]
            CorrectionalBehavioralHealthCertificationEnum = 34,
            [EnumMember(Value = "Certified Continence Care Nurse")]
            CertifiedContinenceCareNurseEnum = 35,
            [EnumMember(Value = "Certified Continence Care Nurse-Advanced Practice")]
            CertifiedContinenceCareNurseAdvancedPracticeEnum = 36,
            [EnumMember(Value = "Certified Childbirth Educator")]
            CertifiedChildbirthEducatorEnum = 37,
            [EnumMember(Value = "Certified Correctional Health Professional-Advanced")]
            CertifiedCorrectionalHealthProfessionalAdvancedEnum = 38,
            [EnumMember(Value = "Certified Correctional Health Professional-RN")]
            CertifiedCorrectionalHealthProfessionalRNEnum = 39,
            [EnumMember(Value = "Certified Clinical Hemodialysis Technician")]
            CertifiedClinicalHemodialysisTechnicianEnum = 40,
            [EnumMember(Value = "Certified Clinical Hemodialysis Technician-Advanced")]
            CertifiedClinicalHemodialysisTechnicianAdvancedEnum = 41,
            [EnumMember(Value = "Acute/Critical Care Clinical Nurse Specialist (Adult, Pediatric & Neonatal)")]
            AcuteCriticalCareClinicalNurseSpecialistAdultPediatricNeonatalEnum = 42,
            [EnumMember(Value = "Certified Clinical Research Associate")]
            CertifiedClinicalResearchAssociateEnum = 43,
            [EnumMember(Value = "Certified Clinical Research Coordinator")]
            CertifiedClinicalResearchCoordinatorEnum = 44,
            [EnumMember(Value = "Acute/Critical Care Nursing (Adult, Pediatric & Neonatal)")]
            AcuteCriticalCareNursingAdultPediatricNeonatalEnum = 45,
            [EnumMember(Value = "Tele-ICU Acute/Critical Care Nursing (Adult)")]
            TeleICUAcuteCriticalCareNursingAdultEnum = 46,
            [EnumMember(Value = "Acute/Critical Care Knowledge Professional (Adult, Pediatric & Neonatal)")]
            AcuteCriticalCareKnowledgeProfessionalAdultPediatricNeonatalEnum = 47,
            [EnumMember(Value = "Certified Clinical Research Professional")]
            CertifiedClinicalResearchProfessionalEnum = 48,
            [EnumMember(Value = "Certified in Care Coordination and Transition Management")]
            CertifiedInCareCoordinationAndTransitionManagementEnum = 49,
            [EnumMember(Value = "Certified Dialysis Licensed Practical Nurse")]
            CertifiedDialysisLicensedPracticalNurseEnum = 50,
            [EnumMember(Value = "Certified Dialysis Licensed Vocational Nurse")]
            CertifiedDialysisLicensedVocationalNurseEnum = 51,
            [EnumMember(Value = "Certified Diabetes Educator")]
            CertifiedDiabetesEducatorEnum = 52,
            [EnumMember(Value = "Certified Dialysis Nurse")]
            CertifiedDialysisNurseEnum = 53,
            [EnumMember(Value = "Certified Emergency Nurse")]
            CertifiedEmergencyNurseEnum = 54,
            [EnumMember(Value = "Certified in Executive Nursing Practice")]
            CertifiedInExecutiveNursingPracticeEnum = 55,
            [EnumMember(Value = "Certified Foot Care Nurse")]
            CertifiedFootCareNurseEnum = 56,
            [EnumMember(Value = "Certified Flight Registered Nurse")]
            CertifiedFlightRegisteredNurseEnum = 57,
            [EnumMember(Value = "Certified Gastroenterology Registered Nurse")]
            CertifiedGastroenterologyRegisteredNurseEnum = 58,
            [EnumMember(Value = "Certified Heart Failure Nurse")]
            CertifiedHeartFailureNurseEnum = 59,
            [EnumMember(Value = "Non-Clinical HeartFailure Nurse")]
            NonClinicalHeartFailureNurseEnum = 60,
            [EnumMember(Value = "Certified Hospice and Palliative Care Administrator")]
            CertifiedHospiceAndPalliativeCareAdministratorEnum = 61,
            [EnumMember(Value = "Certified Hospice and Palliative Licensed Nurse")]
            CertifiedHospiceAndPalliativeLicensedNurseEnum = 62,
            [EnumMember(Value = "Certified Hospice and Palliative Nurse")]
            CertifiedHospiceAndPalliativeNurseEnum = 63,
            [EnumMember(Value = "Certified Hospice and Palliative Nursing Assistant")]
            CertifiedHospiceAndPalliativeNursingAssistantEnum = 64,
            [EnumMember(Value = "Certified Hospice and Palliative Pediatric Nurse")]
            CertifiedHospiceAndPalliativePediatricNurseEnum = 65,
            [EnumMember(Value = "Certified Health Service Administrator")]
            CertifiedHealthServiceAdministratorEnum = 66,
            [EnumMember(Value = "Certified Lactation Counselor")]
            CertifiedLactationCounselorEnum = 67,
            [EnumMember(Value = "Certified in Infection Control")]
            CertifiedInInfectionControlEnum = 68,
            [EnumMember(Value = "Occupational Health Nursing Case Management")]
            OccupationalHealthNursingCaseManagementEnum = 69,
            [EnumMember(Value = "Cardiac Medicine (Adult)")]
            CardiacMedicineAdultEnum = 70,
            [EnumMember(Value = "Certification in Managed Care Nursing")]
            CertificationInManagedCareNursingEnum = 71,
            [EnumMember(Value = "Certified Medical-Surgical Registered Nurse")]
            CertifiedMedicalSurgicalRegisteredNurseEnum = 72,
            [EnumMember(Value = "Certified Ambulatory Surgery Nurse")]
            CertifiedAmbulatorySurgeryNurseEnum = 73,
            [EnumMember(Value = "Certified Nurse Educator")]
            CertifiedNurseEducatorEnum = 74,
            [EnumMember(Value = "Certified Academic Clinical Nurse Educator")]
            CertifiedAcademicClinicalNurseEducatorEnum = 75,
            [EnumMember(Value = "Clinical Nurse Leader")]
            ClinicalNurseLeaderEnum = 76,
            [EnumMember(Value = "Nurse Manager and Leader")]
            NurseManagerAndLeaderEnum = 77,
            [EnumMember(Value = "Certified Nurse Manager and Leader")]
            CertifiedNurseManagerAndLeaderEnum = 78,
            [EnumMember(Value = "Certified Corrections Nurse")]
            CertifiedCorrectionsNurseEnum = 79,
            [EnumMember(Value = "Certified Nephrology Nurse")]
            CertifiedNephrologyNurseEnum = 80,
            [EnumMember(Value = "Certified Nephrology Nurse-Nurse Practitioner")]
            CertifiedNephrologyNurseNursePractitionerEnum = 81,
            [EnumMember(Value = "Certified Corrections Nurse/Manager")]
            CertifiedCorrectionsNurseManagerEnum = 82,
            [EnumMember(Value = "Certified Perioperative Nurse")]
            CertifiedPerioperativeNurseEnum = 83,
            [EnumMember(Value = "Certified Neuroscience Registered Nurse")]
            CertifiedNeuroscienceRegisteredNurseEnum = 84,
            [EnumMember(Value = "Clinical Nurse Specialist, Core")]
            ClinicalNurseSpecialistCoreEnum = 85,
            [EnumMember(Value = "Certified Clinical Nurse Specialist Perioperative")]
            CertifiedClinicalNurseSpecialistPerioperativeEnum = 86,
            [EnumMember(Value = "Certified Ostomy Care Nurse")]
            CertifiedOstomyCareNurseEnum = 87,
            [EnumMember(Value = "Certified Ostomy Care Nurse-Advanced Practice")]
            CertifiedOstomyCareNurseAdvancedPracticeEnum = 88,
            [EnumMember(Value = "Certified Occupational Health Nurse")]
            CertifiedOccupationalHealthNurseEnum = 89,
            [EnumMember(Value = "Certified Occupational Health Nurse-Specialist")]
            CertifiedOccupationalHealthNurseSpecialistEnum = 90,
            [EnumMember(Value = "Certified Otorhinolaryngology Nurse")]
            CertifiedOtorhinolaryngologyNurseEnum = 91,
            [EnumMember(Value = "Certified Post Anesthesia Nurse")]
            CertifiedPostAnesthesiaNurseEnum = 92,
            [EnumMember(Value = "Certified Pediatric Emergency Nurse")]
            CertifiedPediatricEmergencyNurseEnum = 93,
            [EnumMember(Value = "Certified Pediatric Hematology Oncology Nurse")]
            CertifiedPediatricHematologyOncologyNurseEnum = 94,
            [EnumMember(Value = "Certified Professional in Healthcare Quality")]
            CertifiedProfessionalInHealthcareQualityEnum = 95,
            [EnumMember(Value = "Certified Professional in Healthcare Risk Management")]
            CertifiedProfessionalInHealthcareRiskManagementEnum = 96,
            [EnumMember(Value = "Certified in Perinatal Loss Care")]
            CertifiedInPerinatalLossCareEnum = 97,
            [EnumMember(Value = "Certified Pediatric Nurse")]
            CertifiedPediatricNurseEnum = 98,
            [EnumMember(Value = "Certified Pediatric Nurse Practitioner-Primary Care")]
            CertifiedPediatricNursePractitionerPrimaryCareEnum = 99,
            [EnumMember(Value = "Certified Pediatric Oncology Nurse")]
            CertifiedPediatricOncologyNurseEnum = 100,
            [EnumMember(Value = "Certified Pediatric Nurse Practitioner-Acute Care")]
            CertifiedPediatricNursePractitionerAcuteCareEnum = 101,
            [EnumMember(Value = "Certified Plastic Surgical Nurse")]
            CertifiedPlasticSurgicalNurseEnum = 102,
            [EnumMember(Value = "Certified Radiologic Nurse")]
            CertifiedRadiologicNurseEnum = 103,
            [EnumMember(Value = "Certified Registered Nurse Anesthetist")]
            CertifiedRegisteredNurseAnesthetistEnum = 104,
            [EnumMember(Value = "Certified Registered Nurse First Assistant")]
            CertifiedRegisteredNurseFirstAssistantEnum = 105,
            [EnumMember(Value = "Certified Registered Nurse Infusion")]
            CertifiedRegisteredNurseInfusionEnum = 106,
            [EnumMember(Value = "Certification for Registered Nurses of Ophthalmology")]
            CertificationForRegisteredNursesOfOphthalmologyEnum = 107,
            [EnumMember(Value = "Certified Rehabilitation Registered Nurse")]
            CertifiedRehabilitationRegisteredNurseEnum = 108,
            [EnumMember(Value = "Cardiac Surgery (Adult)")]
            CardiacSurgeryAdultEnum = 109,
            [EnumMember(Value = "Certified Surgical Services Manager")]
            CertifiedSurgicalServicesManagerEnum = 110,
            [EnumMember(Value = "Certified Transport Registered Nurse")]
            CertifiedTransportRegisteredNurseEnum = 111,
            [EnumMember(Value = "Urologic Associate")]
            UrologicAssociateEnum = 112,
            [EnumMember(Value = "Certified Urologic Nurse Practitioner")]
            CertifiedUrologicNursePractitionerEnum = 113,
            [EnumMember(Value = "Certified Urologic Registered Nurse")]
            CertifiedUrologicRegisteredNurseEnum = 114,
            [EnumMember(Value = "Certified Wound Care Nurse")]
            CertifiedWoundCareNurseEnum = 115,
            [EnumMember(Value = "Certified Wound Care Nurse-Advanced Practice")]
            CertifiedWoundCareNurseAdvancedPracticeEnum = 116,
            [EnumMember(Value = "Certified Wound Ostomy Continence Nurse")]
            CertifiedWoundOstomyContinenceNurseEnum = 117,
            [EnumMember(Value = "Certified Wound Ostomy Continence Nurse-Advanced Practice")]
            CertifiedWoundOstomyContinenceNurseAdvancedPracticeEnum = 118,
            [EnumMember(Value = "Certified Wound Ostomy Nurse")]
            CertifiedWoundOstomyNurseEnum = 119,
            [EnumMember(Value = "Certified Wound Ostomy Nurse-Advanced Practice")]
            CertifiedWoundOstomyNurseAdvancedPracticeEnum = 120,
            [EnumMember(Value = "Dermatology Certified Nurse Practitioner")]
            DermatologyCertifiedNursePractitionerEnum = 121,
            [EnumMember(Value = "Dermatology Nurse Certified")]
            DermatologyNurseCertifiedEnum = 122,
            [EnumMember(Value = "Emergency Nurse Practitioner (specialty certification)")]
            EmergencyNursePractitionerSpecialtyCertificationEnum = 123,
            [EnumMember(Value = "Family Nurse Practitioner")]
            FamilyNursePractitionerEnum = 124,
            [EnumMember(Value = "Gerontological Nurse Practitioner")]
            GerontologicalNursePractitionerEnum = 125,
            [EnumMember(Value = "Holistic Nurse, Board Certified")]
            HolisticNurseBoardCertifiedEnum = 126,
            [EnumMember(Value = "Holistic Baccalaureate Nurse, Board Certified")]
            HolisticBaccalaureateNurseBoardCertifiedEnum = 127,
            [EnumMember(Value = "Health and Wellness Nurse Coach, Board Certified")]
            HealthAndWellnessNurseCoachBoardCertifiedEnum = 128,
            [EnumMember(Value = "International Board Certified Lactation Consultant")]
            InternationalBoardCertifiedLactationConsultantEnum = 129,
            [EnumMember(Value = "Legal Nurse Consultant Certified")]
            LegalNurseConsultantCertifiedEnum = 130,
            [EnumMember(Value = "Nurse Coach, Board Certified")]
            NurseCoachBoardCertifiedEnum = 131,
            [EnumMember(Value = "National Certified School Nurse")]
            NationalCertifiedSchoolNurseEnum = 132,
            [EnumMember(Value = "Nurse Executive")]
            NurseExecutiveEnum = 133,
            [EnumMember(Value = "Nurse Executive, Advanced")]
            NurseExecutiveAdvancedEnum = 134,
            [EnumMember(Value = "NNP-BC - Neonatal Nurse Practitioner")]
            NNPBCNeonatalNursePractitionerEnum = 135,
            [EnumMember(Value = "Adult Nurse Practitioner")]
            AdultNursePractitionerEnum_136 = 136,
            [EnumMember(Value = "Oncology Certified Nurse")]
            OncologyCertifiedNurseEnum = 137,
            [EnumMember(Value = "Orthopaedic Clinical Nurse Specialist - Certified")]
            OrthopaedicClinicalNurseSpecialistCertifiedEnum = 138,
            [EnumMember(Value = "Orthopaedic Nurse Certified")]
            OrthopaedicNurseCertifiedEnum = 139,
            [EnumMember(Value = "Orthopaedic Nurse Practitioner-Certified")]
            OrthopaedicNursePractitionerCertifiedEnum = 140,
            [EnumMember(Value = "Progressive Care Nursing (Adult)")]
            ProgressiveCareNursingAdultEnum = 141,
            [EnumMember(Value = "Progressive Care Knowledge Professional (Adult)")]
            ProgressiveCareKnowledgeProfessionalAdultEnum = 142,
            [EnumMember(Value = "Pediatric Clinical Nurse Specialist")]
            PediatricClinicalNurseSpecialistEnum = 143,
            [EnumMember(Value = "Public/Community Health Clinical Nurse Specialist (retired exam)")]
            PublicCommunityHealthClinicalNurseSpecialistRetiredExamEnum = 144,
            [EnumMember(Value = "Pediatric Primary Care Mental Health Specialist")]
            PediatricPrimaryCareMentalHealthSpecialistEnum = 145,
            [EnumMember(Value = "Public Health Nursing, Advanced")]
            PublicHealthNursingAdvancedEnum = 146,
            [EnumMember(Value = "Adult Psychiatric-Mental Health Clinical Nurse Specialist")]
            AdultPsychiatricMentalHealthClinicalNurseSpecialistEnum = 147,
            [EnumMember(Value = "Child/Adolescent Psychiatric-Mental Health Clinical Nurse Specialist")]
            ChildAdolescentPsychiatricMentalHealthClinicalNurseSpecialistEnum = 148,
            [EnumMember(Value = "Adult Psychiatric-Mental Health Nurse Practitioner")]
            AdultPsychiatricMentalHealthNursePractitionerEnum = 149,
            [EnumMember(Value = "Psychiatric-Mental Health Nurse Practitioner (across the life span)")]
            PsychiatricMentalHealthNursePractitionerAcrossTheLifeSpanEnum = 150,
            [EnumMember(Value = "Pediatric Primary Care Nurse Practitioner")]
            PediatricPrimaryCareNursePractitionerEnum = 151,
            [EnumMember(Value = "Ambulatory Care Nursing")]
            AmbulatoryCareNursingEnum = 152,
            [EnumMember(Value = "Cardiac-Vascular Nursing")]
            CardiacVascularNursingEnum = 153,
            [EnumMember(Value = "Certified Vascular Nurse (retired exam)")]
            CertifiedVascularNurseRetiredExamEnum = 154,
            [EnumMember(Value = "College Health Nursing (retired exam)")]
            CollegeHealthNursingRetiredExamEnum = 155,
            [EnumMember(Value = "Community Health Nursing (retired exam)")]
            CommunityHealthNursingRetiredExamEnum = 156,
            [EnumMember(Value = "Faith Community Nursing")]
            FaithCommunityNursingEnum = 157,
            [EnumMember(Value = "Genetics Nursing, Advanced")]
            GeneticsNursingAdvancedEnum_158 = 158,
            [EnumMember(Value = "General Nursing, Practice (retired exam)")]
            GeneralNursingPracticeRetiredExamEnum = 159,
            [EnumMember(Value = "Gerontological Nursing")]
            GerontologicalNursingEnum = 160,
            [EnumMember(Value = "Hemostasis Nursing")]
            HemostasisNursingEnum = 161,
            [EnumMember(Value = "High-Risk Perinatal Nursing (retired exam)")]
            HighRiskPerinatalNursingRetiredExamEnum = 162,
            [EnumMember(Value = "Home Health Nursing (retired exam)")]
            HomeHealthNursingRetiredExamEnum = 163,
            [EnumMember(Value = "Informatics Nursing")]
            InformaticsNursingEnum = 164,
            [EnumMember(Value = "Medical-Surgical Nursing")]
            MedicalSurgicalNursingEnum = 165,
            [EnumMember(Value = "Nursing Case Management")]
            NursingCaseManagementEnum = 166,
            [EnumMember(Value = "Nursing Professional Development")]
            NursingProfessionalDevelopmentEnum = 167,
            [EnumMember(Value = "Pain Management Nursing")]
            PainManagementNursingEnum = 168,
            [EnumMember(Value = "Pediatric Nursing")]
            PediatricNursingEnum = 169,
            [EnumMember(Value = "Perinatal Nursing (retired exam)")]
            PerinatalNursingRetiredExamEnum = 170,
            [EnumMember(Value = "Psychiatric-Mental Health Nursing")]
            PsychiatricMentalHealthNursingEnum = 171,
            [EnumMember(Value = "Public Health Nursing, Advanced")]
            PublicHealthNursingAdvancedEnum_172 = 172,
            [EnumMember(Value = "Rheumatology Nursing")]
            RheumatologyNursingEnum = 173,
            [EnumMember(Value = "School Nursing (retired exam)")]
            SchoolNursingRetiredExamEnum = 174,
            [EnumMember(Value = "RNC-LRN - Low Risk Neonatal Nursing")]
            RNCLRNLowRiskNeonatalNursingEnum = 175,
            [EnumMember(Value = "RNC-MNN - Maternal Newborn Nursing")]
            RNCMNNMaternalNewbornNursingEnum = 176,
            [EnumMember(Value = "RNC-NIC - Neonatal Intensive Care Nursing")]
            RNCNICNeonatalIntensiveCareNursingEnum = 177,
            [EnumMember(Value = "RNC-OB - Inpatient Obstetric Nursing")]
            RNCOBInpatientObstetricNursingEnum = 178,
            [EnumMember(Value = "Sexual Assault Nurse Examiner - Adult/Adolescent")]
            SexualAssaultNurseExaminerAdultAdolescentEnum = 179,
            [EnumMember(Value = "Sexual Assault Nurse Examiner - Pediatric")]
            SexualAssaultNurseExaminerPediatricEnum = 180,
            [EnumMember(Value = "Stroke Certified Registered Nurse")]
            StrokeCertifiedRegisteredNurseEnum = 181,
            [EnumMember(Value = "School Nurse Practitioner (retired exam)")]
            SchoolNursePractitionerRetiredExamEnum = 182,
            [EnumMember(Value = "Trauma Certified Registered Nurse")]
            TraumaCertifiedRegisteredNurseEnum = 183,
            [EnumMember(Value = "WHNP-BC - Women’s Health Care Nurse Practitioner")]
            WHNPBCWomensHealthCareNursePractitionerEnum = 184
        }

        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum LicenseCertificationStatusCEnum
        {
            [EnumMember(Value = "Active")]
            ActiveEnum = 0,
            [EnumMember(Value = "Expired")]
            ExpiredEnum = 1
        }
    }
}
